# Location of backup working directory
workdir: /var/mediawiki-backup/wiki/

# Location of mediawiki web application
wikidir: /var/www/html/wiki/

# Setting file name of mediawiki
local_settings_file: LocalSettings.php

#-----------------------------------------------------------
# About MySQL or MariaDB data
#-----------------------------------------------------------

# Location of mysql db backup
mysqldump_dir: /var/mediawiki-backup/wiki/db

# Prefix of mysqldump file
mysqldump_file_prefix: mysql-dump

# Generation to save mysqldump
mysqldump_generation_num: 30

#-----------------------------------------------------------
# About mediawiki files
#-----------------------------------------------------------

# Location of mediawiki files backup
mediawiki_backup_dir: /var/mediawiki-backup/wiki/files

# Prefix of mediawiki file
mediawiki_backup_file_prefix: mediawiki-backup

# Generation to save mediawiki backup
mediawiki_backup_generation: 30

# Retry num for determin backup file suffix
define_file_name_retry_num: 5

#-----------------------------------------------------------
# About mail
#-----------------------------------------------------------

# E-mail recipient address.
# An error mail will be sent when this script encountered some errors.
# Make empty this value if you won't send email whether the script will encounter errors or not.
#mail_recipient_address: bar@example.com
mail_recipient_address:

# E-mail recipient name.
# This value is optional.
mail_recipient_name: Someone's mail address

# E-mail sender.
# This value is required if value of mail_recipient is filled.
mail_sender_address: server-admin@example.com

# E-mail sender name.
# This value is optional
mail_sender_name: Server administrator

# MTA to send e-mail.
# This value is required if value of mail_recipient is filled.
mail_mta_host: localhost

# Port of MTA host to send e-mail.
# This value is required if value of mail_recipient is filled.
mail_mta_port: 25

