#-----------------------------------------------------------
# General configuration options.
#
# These options may be changed frequently due to your environment.
#-----------------------------------------------------------
# Location of mediawiki web application
wikidir: /var/www/wiki/

# Setting file name of mediawiki
local_settings_file: LocalSettings.php

# Location of mysql db backup
mysqldump_dir: /var/mediawiki-backup/wiki/db

# Location of mediawiki files backup
mediawiki_backup_dir: /var/mediawiki-backup/wiki/files

#-----------------------------------------------------------
# About MySQL or MariaDB backup data.
#
# The credentials of MySQL or MariaDB will be acquired from
# the file that assigned 'local_settings_file'
# (generally, LocalSettings.php).
#-----------------------------------------------------------
# Prefix of mysqldump file
mysqldump_file_prefix: mysql-dump

# Generation to save mysqldump
mysqldump_generation_num: 720

# Timeout for mysqldump command
mysqldump_timeout_sec: 300

#-----------------------------------------------------------
# About mediawiki backup files or others
#-----------------------------------------------------------
# Prefix of mediawiki file
mediawiki_backup_file_prefix: mediawiki-backup

# Generation to save mediawiki backup
mediawiki_backup_generation: 720

# Retry num for determin backup file suffix
define_file_name_retry_num: 5

# Location of backup working directory
workdir: /var/tmp/mediawiki

